### ISSUE TITLE
Something in the Rifts.dat File Errors

### ISSUE THREAD

**Issue by ravengode** [TCArknight/Savage-Rifts#11]
When I load the rifts.dat file into HL and a launch it 2 errors of the same type occur:

Thing 'vhCSpa09A' - Bootstrap thing 'wplZTAWUG' does not exist

This error prevents the Rifts setting from loading. 
When I delete this file from HL it loads the setting (it allows the Rifts setting and CS Manual to be checked) but there is nothing from the setting in the Heroes Journey or Races.

**Comment by TCArknight** [comment]
This is bootstrapping the Grenade Launcher from Interface Zero files instead of the correct one. Working on fixing.

**Comment by TCArknight** [comment]
Fixed
