### ISSUE TITLE
Hero's Journey Missing an Edge

### ISSUE THREAD

**Issue by ravengode** [TCArknight/Savage-Rifts#15]
On the Experience and Wisdom Heroic Journey table there is the Background Edge option. When selected it is missing the Background Edge Fleet Footed as an option to select.

**Comment by ravengode** [comment]
More specifically, it looks like you have Fleet Footed under combat edges, when it should be a background edge

**Comment by ravengode** [comment]
Looks like CapedCrusader will fix in the main HL for the next update. I assume that will resolve this problem.

**Comment by TCArknight** [comment]
This will resolve when changed in main dataset. :)
