### ISSUE TITLE
issue with strength trait

### ISSUE THREAD

**Issue by Lufengxl** [TCArknight/Savage-Rifts#20]
noticed when i have a str of d12+5 it only gives an encumberance/load limit of 110 rather than the 2500 it should be,  if i click on the "super powers companion 2" in the configure hero section it will jump up to the 2500 load limit, but then in the advances->new edges there is no longer a "new power" edge so i can add arcane powers.

Thanks

**Comment by TCArknight** [comment]
Let me take a look at that. :)

**Comment by TCArknight** [comment]
Fixed in next release
